export const DEFAULT_DIRECT_SWEEPER_BASE_URL = 'https://mobilelab.xend.africa';
export const DEFAULT_DIRECT_SWEEP_HOUR_UTC = 7;
export const DEFAULT_DIRECT_SWEEP_MINUTE_UTC = 0;
export const DEFAULT_DIRECT_SWEEP_DERIVATION_SEARCH_WINDOW = 20_000;
export const DEFAULT_DIRECT_SWEEP_DERIVATION_MAX_INDEX = 500_000;
